// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostOfficeBackendProject.src.Infrastructure.Data;

#nullable disable

namespace PostOfficeBackendProject.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20251105061027_updateCustomerAndPostmanTable")]
    partial class updateCustomerAndPostmanTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.PostOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeAccessCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StorageCapacity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PostOffice");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.Postman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PersonalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostOfficeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostOfficeId");

                    b.ToTable("Postman");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostOfficeId")
                        .HasColumnType("int");

                    b.Property<int?>("PostmanId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("TransportStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PostOfficeId");

                    b.HasIndex("PostmanId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("TransportStatusId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductType");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("DeliverCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliverdDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PostOfficeId")
                        .HasColumnType("int");

                    b.Property<int>("PostmanId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PostOfficeId");

                    b.HasIndex("PostmanId");

                    b.HasIndex("ProductId");

                    b.ToTable("Transport");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.TransportStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransportStatus");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.Postman", b =>
                {
                    b.HasOne("PostOfficeBackendProject.src.Domain.Model.PostOffice", "PostOffice")
                        .WithMany("Postman")
                        .HasForeignKey("PostOfficeId");

                    b.Navigation("PostOffice");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.Product", b =>
                {
                    b.HasOne("PostOfficeBackendProject.src.Domain.Model.Customer", "Customer")
                        .WithMany("Products")
                        .HasForeignKey("CustomerId");

                    b.HasOne("PostOfficeBackendProject.src.Domain.Model.PostOffice", "PostOffice")
                        .WithMany("Products")
                        .HasForeignKey("PostOfficeId");

                    b.HasOne("PostOfficeBackendProject.src.Domain.Model.Postman", "Postman")
                        .WithMany("Products")
                        .HasForeignKey("PostmanId");

                    b.HasOne("PostOfficeBackendProject.src.Domain.Model.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId");

                    b.HasOne("PostOfficeBackendProject.src.Domain.Model.TransportStatus", "TransportStatus")
                        .WithMany("Product")
                        .HasForeignKey("TransportStatusId");

                    b.Navigation("Customer");

                    b.Navigation("PostOffice");

                    b.Navigation("Postman");

                    b.Navigation("ProductType");

                    b.Navigation("TransportStatus");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.Transport", b =>
                {
                    b.HasOne("PostOfficeBackendProject.src.Domain.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("PostOfficeBackendProject.src.Domain.Model.PostOffice", "PostOffice")
                        .WithMany("Transport")
                        .HasForeignKey("PostOfficeId");

                    b.HasOne("PostOfficeBackendProject.src.Domain.Model.Postman", "Postman")
                        .WithMany()
                        .HasForeignKey("PostmanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PostOfficeBackendProject.src.Domain.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Customer");

                    b.Navigation("PostOffice");

                    b.Navigation("Postman");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.Customer", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.PostOffice", b =>
                {
                    b.Navigation("Postman");

                    b.Navigation("Products");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.Postman", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("PostOfficeBackendProject.src.Domain.Model.TransportStatus", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
